language: node_js
node_js:
- '10'
dist: bionic
group: dev
sudo: false
services:
- redis-server
- postgresql
addons:
  chrome: stable
  postgresql: '10'
  apt:
    packages:
    - autoconf
    - bison
    - build-essential
    - ffmpeg
    - file
    - g++
    - gcc
    - imagemagick
    - libffi-dev
    - libgdbm5
    - libicu-dev
    - libidn11-dev
    - libncurses5-dev
    - libpq-dev
    - libprotobuf-dev
    - libreadline6-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - pkg-config
    - postgresql-client-10
    - postgresql-contrib-10
    - protobuf-compiler
    - redis-server
    - redis-tools
    - zlib1g-dev
    - fonts-noto-color-emoji
before_install:
- psql -d template1 -U postgres -c "CREATE USER pinafore WITH PASSWORD 'pinafore'
  CREATEDB;"
- curl -o- -L https://yarnpkg.com/install.sh | bash -s
- export PATH="$HOME/.yarn/bin:$PATH"
- "./bin/setup-mastodon-in-travis.sh"
before_script:
- yarn run lint
after_script:
- rm -f /home/travis/.rvm/gems/ruby-*/bin/posix-spawn-benchmark
script: travis_retry yarn run $COMMAND
env:
  global:
  - ESM_DISABLE_CACHE=1
  - TERSER_DISABLE_CACHE=1
  - secure: kLsuDI1c2/g72Ek2dQZCxpKiEwkSNzB73zddeHyQ/BPNis0FKz172ul28Oeq1eb+tfg51nWq43NBCQ5PtHAjF+O7DbHR1+shj0dyQgMk86aZDVQTp4o5dX3hWyM04apc9hVUVqrCsCP3bHztcdyBu6Lb2QC2dlz8tfYxytcd0T1sQYd08Z5F3jf3rCASccAZ1XS+w3a3yQoD/uu9nsQCIgGpDRGNAt6mPGw4zk8ZmpswA6XPTsfaNZFhln72yQWVCOl+7WD8S2qiBGEXONaVz4/LB/1uo9+i2iPIMhOON91oi0SSacxfYAVsV0wh4L2IEhkbLBvPYI4lelV39U0asTEHBcQmay73KQr8K4aYK7NnK7NK56W/vlJXd6c2Qd0NtUmY5yTGPBJQHtGCDSXIHijXHlmA+NGwJfoDUL7QDNAoC0StR8uSPnAQ4NdfheBSf6l7kKOo5HZwjK4JTWfTvr549TMJnFr9fYNJii9W/MyajLed0wF5nPJ50VyIXX9BAMa7n8KSQ1YV0W9Kp88LHAfASUGjo2P5IddgC3CaM/WAoMWOW5D3vWCWhIQzSmJLz66vUqi3oaiglw+/Q77nrDDE+2zkQGCl6Ehof27TFJRMu2QnT6El3upsRfnMgV3MdO3Kd2Pq0iFSXqPZQIAyba1LAQcveh/OPWmKWjzGkew=
matrix:
  include:
  - env: BROWSER=chrome:headless COMMAND=test-browser-suite0
  - env: BROWSER=chrome:headless COMMAND=test-browser-suite1
  - env: COMMAND=test-unit
  - env: COMMAND=deploy-all-travis
  allow_failures:
  - env: COMMAND=deploy-all-travis
branches:
  only:
  - master
cache:
  yarn: true
  bundler: true
  directories:
  - "/home/travis/.rvm/"
